import { Metadata } from "next"

export const metadata:Metadata = {
  title: {
	default:"Defualt Title",
	template:"%s | Template",
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
		<header style={{backgroundColor:"lightblue",padding:"1rem",}}>
			<p>Header</p>
		</header>
		{children}
		<footer style={{backgroundColor:"ghostWhite",padding:"1rem",}}>
			<p>Footer</p>
		</footer>
		</body>
    </html>
  )
}
